# 行列積

以下のような行列A、Bを考えます。

A = [[-1, 2, 3], [4, -5, 6], [7, 8, -9]]

B = [[0, 2, 1], [0, 2, -8], [2, 9, -1]]

NumPyで表すと次のようになります。

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 【問題1】行列積を手計算する

AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

A,Bともに3行3列により行列積を行う。
計算過程は以下となる。

-1*0+2*0+3*2  -1*2+2*2+3*9 -1*1+(-8*2)+3*-1

4*0+(-5*0)+6*2 2*4+2*-5+9*6 4*1+(-5*-8)+6*-1

7*0+8*0-9*2    7*2+8*2+9*-9 7*1+8*-8+(-9*-1)

↓

 6 29 -20
 
 12 52 38
 
-18 -51 -48

# 【問題2】NumPyの関数による計算

この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul

https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

《3種類の違い》

np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。

今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。

If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

In [4]:
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [6]:
np.dot(a_ndarray, b_ndarray) #動作確認、今回は適当ではない

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 行列積のスクラッチ実装

np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。

# 【問題3】ある要素の計算を実装

手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。
1. 行列Aの(0,0)の要素 a0,0a0,0 と行列Bの(0,0)の要素 b0,0b0,0 を掛け合わせる
2. 行列Aの(0,1)の要素 a0,1a0,1 と行列Bの(1,0)の要素 b1,0b1,0 を掛け合わせる
3. 行列Aの(0,2)の要素 a0,2a0,2 と行列Bの(2,0)の要素 b2,0b2,0 を掛け合わせる
4. それらの値を全て足し合わせる

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [9]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

ndarray_0 = (a_ndarray[0]* b_ndarray[:,0]) .sum()

print(" Aの0行目とBの0列目：{}".format(ndarray_0))

 Aの0行目とBの0列目：6


# 【問題4】行列積を行う関数の作成

問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。
行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。
計算結果である 3×33×3 の行列Cの各要素 ci,jci,j は数式で表すと次のようになります。

https://diver.diveintocode.jp/curriculums/1630 参照

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックスiやjを1増やすと、次の行や列に移ることができます。

In [43]:
def matrix_multiplication_calculation(a,b):
    c = np.empty((a.shape[0], b.shape[1]))
    
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[i, j] = (a[i]*b[:, j]).sum() # c[i, j]のところ考える必要あり
    return c

In [46]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print("計算結果\n{}".format(matrix_multiplication_calculation(a_ndarray, b_ndarray)))

計算結果
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# 行列積が定義されない組み合わせの行列

次に以下のような例を考えます。

In [47]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

In [48]:
d_ndarray.shape

(2, 3)

In [49]:
e_ndarray.shape

(2, 3)

# 【問題5】計算が定義されない入力を判定する

問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [50]:
def matrix_multiplication_calculation2(a,b):
    c = np.empty((a.shape[0], b.shape[1]))
    
    if a.shape[1] == b.shape[0]:


        for i in range(a.shape[0]):
            for j in range(b.shape[1]):
                c[i, j] = (a[i]*b[:, j]).sum() # c[i, j]のところ考える必要あり
        return c
    else:
        print("入力される形に問題があります")

In [51]:
matrix_multiplication_calculation2(d_ndarray,e_ndarray)

入力される形に問題があります


In [52]:
matrix_multiplication_calculation2(a_ndarray,b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

# 【問題6】転置

片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html

In [53]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

np.matmul(d_ndarray, e_ndarray.T)

array([[ 46,  -4],
       [-34,  73]])

In [54]:
np.matmul(d_ndarray.T, e_ndarray)

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])